### ISSUE TITLE
can't receive emails on public schema

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#1129]
at the application apex (eg: taron.cloud)-- receiving emails results in the following error: 

``` txt
2022-09-25T21:55:21.765789377Z app[web.1]: I, [2022-09-25T21:55:21.765708 #190]  INFO -- : [d5b80bab-03cb-4e0a-a4f3-103e357548a9] Completed 400 Bad Request in 3ms (ActiveRecord: 0.0ms | Allocations: 900)
2022-09-25T21:55:21.768041483Z app[web.1]: F, [2022-09-25T21:55:21.767894 #190] FATAL -- : [d5b80bab-03cb-4e0a-a4f3-103e357548a9]   
2022-09-25T21:55:21.768059272Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] ActionController::ParameterMissing (param is missing or the value is empty: body-mime
2022-09-25T21:55:21.768065451Z app[web.1]: Did you mean?  body-html
2022-09-25T21:55:21.768069804Z app[web.1]:                body-plain
2022-09-25T21:55:21.768074159Z app[web.1]:                domain
2022-09-25T21:55:21.768078290Z app[web.1]:                from):
2022-09-25T21:55:21.768083146Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9]   
2022-09-25T21:55:21.768087644Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_controller/metal/strong_parameters.rb:507:in `require'
2022-09-25T21:55:21.768092269Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionmailbox (6.1.5) app/controllers/action_mailbox/ingresses/mailgun/inbound_emails_controller.rb:54:in `mail'
2022-09-25T21:55:21.768097154Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionmailbox (6.1.5) app/controllers/action_mailbox/ingresses/mailgun/inbound_emails_controller.rb:49:in `create'
2022-09-25T21:55:21.768110189Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
2022-09-25T21:55:21.768113508Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/abstract_controller/base.rb:228:in `process_action'
2022-09-25T21:55:21.768116502Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_controller/metal/rendering.rb:30:in `process_action'
2022-09-25T21:55:21.768119518Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
2022-09-25T21:55:21.768122564Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] activesupport (6.1.5) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
2022-09-25T21:55:21.768125654Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actiontext (6.1.5) lib/action_text/rendering.rb:20:in `with_renderer'
2022-09-25T21:55:21.768128617Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actiontext (6.1.5) lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'
2022-09-25T21:55:21.768132012Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] activesupport (6.1.5) lib/active_support/callbacks.rb:126:in `instance_exec'
2022-09-25T21:55:21.768135095Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] activesupport (6.1.5) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
2022-09-25T21:55:21.768138181Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] ahoy_matey (3.2.0) lib/ahoy/controller.rb:45:in `set_ahoy_request_store'
2022-09-25T21:55:21.768141697Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] activesupport (6.1.5) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
2022-09-25T21:55:21.768144751Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] activesupport (6.1.5) lib/active_support/callbacks.rb:137:in `run_callbacks'
2022-09-25T21:55:21.768148833Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/abstract_controller/callbacks.rb:41:in `process_action'
2022-09-25T21:55:21.768153308Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_controller/metal/rescue.rb:22:in `process_action'
2022-09-25T21:55:21.768157668Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
2022-09-25T21:55:21.768162329Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] activesupport (6.1.5) lib/active_support/notifications.rb:203:in `block in instrument'
2022-09-25T21:55:21.768167055Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] activesupport (6.1.5) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
2022-09-25T21:55:21.768171393Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] activesupport (6.1.5) lib/active_support/notifications.rb:203:in `instrument'
2022-09-25T21:55:21.768174404Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
2022-09-25T21:55:21.768177504Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
2022-09-25T21:55:21.768180521Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] activerecord (6.1.5) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
2022-09-25T21:55:21.768183599Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/abstract_controller/base.rb:165:in `process'
2022-09-25T21:55:21.768189804Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionview (6.1.5) lib/action_view/rendering.rb:39:in `process'
2022-09-25T21:55:21.768192882Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_controller/metal.rb:190:in `dispatch'
2022-09-25T21:55:21.768207317Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_controller/metal.rb:254:in `dispatch'
2022-09-25T21:55:21.768210287Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
2022-09-25T21:55:21.768213455Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_dispatch/routing/route_set.rb:33:in `serve'
2022-09-25T21:55:21.768216679Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_dispatch/journey/router.rb:50:in `block in serve'
2022-09-25T21:55:21.768219586Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_dispatch/journey/router.rb:32:in `each'
2022-09-25T21:55:21.768222515Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_dispatch/journey/router.rb:32:in `serve'
2022-09-25T21:55:21.768225767Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_dispatch/routing/route_set.rb:842:in `call'
2022-09-25T21:55:21.768230087Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] turnout (2.5.0) lib/rack/turnout.rb:25:in `call'
2022-09-25T21:55:21.768234154Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] ros-apartment (2.9.0) lib/apartment/elevators/generic.rb:22:in `block in call'
2022-09-25T21:55:21.768238766Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] ros-apartment (2.9.0) lib/apartment/adapters/abstract_adapter.rb:89:in `switch'
2022-09-25T21:55:21.768243242Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] vendor/ruby-3.0.0/lib/ruby/3.0.0/forwardable.rb:238:in `switch'
2022-09-25T21:55:21.768248037Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] ros-apartment (2.9.0) lib/apartment/elevators/generic.rb:22:in `call'
2022-09-25T21:55:21.768251026Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] exception_notification (4.5.0) lib/exception_notification/rack.rb:49:in `call'
2022-09-25T21:55:21.768253914Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
2022-09-25T21:55:21.768256776Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
2022-09-25T21:55:21.768259611Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] warden (1.2.9) lib/warden/manager.rb:34:in `call'
2022-09-25T21:55:21.768262489Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] rack (2.2.3.1) lib/rack/tempfile_reaper.rb:15:in `call'
2022-09-25T21:55:21.768265358Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] rack (2.2.3.1) lib/rack/etag.rb:27:in `call'
2022-09-25T21:55:21.768268199Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] rack (2.2.3.1) lib/rack/conditional_get.rb:40:in `call'
2022-09-25T21:55:21.768271007Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] rack (2.2.3.1) lib/rack/head.rb:12:in `call'
2022-09-25T21:55:21.768273844Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
2022-09-25T21:55:21.768279825Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_dispatch/http/content_security_policy.rb:19:in `call'
2022-09-25T21:55:21.768282756Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] rack (2.2.3.1) lib/rack/session/abstract/id.rb:266:in `context'
2022-09-25T21:55:21.768286056Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] rack (2.2.3.1) lib/rack/session/abstract/id.rb:260:in `call'
2022-09-25T21:55:21.768288925Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_dispatch/middleware/cookies.rb:689:in `call'
2022-09-25T21:55:21.768291837Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
2022-09-25T21:55:21.768294725Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] activesupport (6.1.5) lib/active_support/callbacks.rb:98:in `run_callbacks'
2022-09-25T21:55:21.768297595Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
2022-09-25T21:55:21.768300461Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
2022-09-25T21:55:21.768303837Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
2022-09-25T21:55:21.768308192Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
2022-09-25T21:55:21.768312298Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] web-console (4.1.0) lib/web_console/middleware.rb:19:in `block in call'
2022-09-25T21:55:21.768316758Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
2022-09-25T21:55:21.768321196Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
2022-09-25T21:55:21.768325601Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
2022-09-25T21:55:21.768328684Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] railties (6.1.5) lib/rails/rack/logger.rb:37:in `call_app'
2022-09-25T21:55:21.768331537Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] railties (6.1.5) lib/rails/rack/logger.rb:26:in `block in call'
2022-09-25T21:55:21.768334414Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] activesupport (6.1.5) lib/active_support/tagged_logging.rb:99:in `block in tagged'
2022-09-25T21:55:21.768337332Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] activesupport (6.1.5) lib/active_support/tagged_logging.rb:37:in `tagged'
2022-09-25T21:55:21.768340264Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] activesupport (6.1.5) lib/active_support/tagged_logging.rb:99:in `tagged'
2022-09-25T21:55:21.768343167Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] railties (6.1.5) lib/rails/rack/logger.rb:26:in `call'
2022-09-25T21:55:21.768346340Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] ahoy_matey (3.2.0) lib/ahoy/engine.rb:22:in `call_with_quiet_ahoy'
2022-09-25T21:55:21.768349377Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
2022-09-25T21:55:21.768352235Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_dispatch/middleware/request_id.rb:26:in `call'
2022-09-25T21:55:21.768361213Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] rack (2.2.3.1) lib/rack/method_override.rb:24:in `call'
2022-09-25T21:55:21.768364176Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] rack (2.2.3.1) lib/rack/runtime.rb:22:in `call'
2022-09-25T21:55:21.768367111Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] activesupport (6.1.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
2022-09-25T21:55:21.768370067Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
2022-09-25T21:55:21.768391113Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_dispatch/middleware/static.rb:24:in `call'
2022-09-25T21:55:21.768395567Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] rack (2.2.3.1) lib/rack/sendfile.rb:110:in `call'
2022-09-25T21:55:21.768399754Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] actionpack (6.1.5) lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
2022-09-25T21:55:21.768404458Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
2022-09-25T21:55:21.768409089Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] railties (6.1.5) lib/rails/engine.rb:539:in `call'
2022-09-25T21:55:21.768413367Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] puma (5.6.4) lib/puma/configuration.rb:252:in `call'
2022-09-25T21:55:21.768416378Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] puma (5.6.4) lib/puma/request.rb:77:in `block in handle_request'
2022-09-25T21:55:21.768419340Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] puma (5.6.4) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
2022-09-25T21:55:21.768422308Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] puma (5.6.4) lib/puma/request.rb:76:in `handle_request'
2022-09-25T21:55:21.768425245Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] puma (5.6.4) lib/puma/server.rb:441:in `process_client'
2022-09-25T21:55:21.768428200Z app[web.1]: [d5b80bab-03cb-4e0a-a4f3-103e357548a9] puma (5.6.4) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by donrestarone** [comment]
affecting nikean.org as well: 


<img width="1308" alt="Screen Shot 2022-12-19 at 8 17 16 AM" src="https://user-images.githubusercontent.com/35935196/208434700-5caab452-25f4-460c-b171-4162bc2cccd8.png">

<img width="1296" alt="Screen Shot 2022-12-19 at 8 17 31 AM" src="https://user-images.githubusercontent.com/35935196/208434693-81325e4d-c067-4152-a9af-935b0f679af3.png">
