### ISSUE TITLE
can't search by name in API #index

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#1225]
when the user enters a query to the form marked below, they get an error
<img width="1728" alt="Screen Shot 2022-11-12 at 3 03 40 PM" src="https://user-images.githubusercontent.com/35935196/201492488-c78805fc-a33a-45c1-9888-30fc0622582e.png">

``` txt
An ActionView::Template::Error occurred in api_namespaces#index:

  PG::UndefinedFunction: ERROR:  operator does not exist: jsonb ~~* unknown
LINE 1: ...i_namespaces" WHERE "api_namespaces"."properties" ILIKE '"%l...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

  app/helpers/application_helper.rb:8:in `page_entries_info'


-------------------------------
Request:
-------------------------------

  * URL        : https://nikean.org/api_namespaces?q%5Bproperties_cont%5D=log&commit=Search
  * HTTP Method: GET
  * IP address : 142.188.123.103
  * Parameters : {"q"=>{"properties_cont"=>"log"}, "commit"=>"Search", "controller"=>"comfy/admin/api_namespaces", "action"=>"index"}
  * Timestamp  : 2022-11-12 20:02:35 UTC
  * Server : ip-172-31-14-250
    * Rails root : /var/www/violet/releases/20221112125222
  * Process: 2267278

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"26e9b7f89827882fd4faf1c99d2f58d8",
   "user_return_to"=>"/api_namespaces?q%5Bproperties_cont%5D=log&commit=Search",
   "warden.user.user.key"=>[[1], "$2a$12$WzLq2Z7gALlIsGWDuPTQQO"],
   "warden.user.user.session"=>{"last_request_at"=>1668283355},
   "site_id"=>1,
   "_csrf_token"=>"x_O-rvehbkha1-ps9UWnlyRpMq7AFefCNHKjxJBbQcg="}

-------------------------------
Environment:
-------------------------------

  * GATEWAY_INTERFACE                                       : CGI/1.2
    * HTTP_ACCEPT                                             : text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    * HTTP_ACCEPT_ENCODING                                    : gzip, deflate, br
    * HTTP_ACCEPT_LANGUAGE                                    : en-CA,en-US;q=0.9,en;q=0.8
    * HTTP_CONNECTION                                         : close
    * HTTP_COOKIE                                             : _r_solutions_session=6%2FIoGAG%2FSYxgRdTg9xjOv4tm4s%2BK%2FByQeFKgbOttnc9H1QDVFNkQcvzF0Gi76sotycq9Q2c79JH4DodT2PHTEwb2jhgm1l1nGr3GVgKMjK9kXYq0a30zKLHLyuCUUwJgEWDW%2B33vmsr3%2FRGhHppS%2FyRaUes6HmVVJ534%2BrlKPfcv8YcE8aKP8ZafG9u%2Fzs4zUA9cidYE6MRszU33rJGYAgb%2FYC2s3Gkh%2BVDo4Fa%2F4%2FSLlWI%2BOs3xjp5jKD3kESuxdSKjU%2FIav6vmYrlGvBaVv3NcBKHSl1boVpmZLzZBrbIVFeIRoZZcbO8h5ksDFq4xRE3n4Bj67PIVz7Y4fCvcOeW2xqjM740gKX4xsFb0ANOTt7GWFI30JDSprlKU7HRUVdFHTVLV6%2BxnYi9dpoc%2BVGIYZCWiRDwvzaEtC3d5a6E84IYbLPV2lIvQbsiX8D4xFAlFmfKwMmwtZgcpmxJ6Em9B1emyHb1F3XZ7Xj4fVJPNmsUDAU%2BU8ViLKKk4sLWb381tccECNiFiLpMYSNTVarTD2ftC3sblALxMWCYvGscEfgxjo55B%2B9AzDfoEbN2drwjclES%2B5yE%3D--Dr31oE2EL2CZ%2FzJo--YGEDbxtRyEwCFu0FZ%2FK3XQ%3D%3D; cookies_accepted=false
    * HTTP_HOST                                               : [nikean.org](http://nikean.org/)
    * HTTP_REFERER                                            : https://nikean.org/api_namespaces?
    * HTTP_USER_AGENT                                         : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15
    * HTTP_VERSION                                            : HTTP/1.0
    * HTTP_X_FORWARDED_FOR                                    : 142.188.123.103
    * HTTP_X_FORWARDED_PROTO                                  : https
    * HTTP_X_REAL_IP                                          : 142.188.123.103
    * ORIGINAL_FULLPATH                                       : /api_namespaces?q%5Bproperties_cont%5D=log&commit=Search
    * ORIGINAL_SCRIPT_NAME                                    :
    * PATH_INFO                                               : /api_namespaces
    * QUERY_STRING                                            : q%5Bproperties_cont%5D=log&commit=Search
    * REMOTE_ADDR                                             : 127.0.0.1
    * REQUEST_METHOD                                          : GET
    * REQUEST_PATH                                            : /api_namespaces
    * REQUEST_URI                                             : /api_namespaces?q%5Bproperties_cont%5D=log&commit=Search
    * ROUTES_46983497317240_SCRIPT_NAME                       :
    * SCRIPT_NAME                                             :
    * SERVER_NAME                                             : [nikean.org](http://nikean.org/)
    * SERVER_PORT                                             : 443
    * SERVER_PROTOCOL                                         : HTTP/1.1
    * SERVER_SOFTWARE                                         : puma 5.6.4 Birdie's Version
    * action_controller.instance                              : #<Comfy::Admin::ApiNamespacesController:0x00007f81cca54ce0>
    * action_dispatch.authenticated_encrypted_cookie_salt     : [FILTERED]
    * action_dispatch.backtrace_cleaner                       : #<Rails::BacktraceCleaner:0x00005576667e1670>
    * action_dispatch.content_security_policy                 :
    * action_dispatch.content_security_policy_nonce_directives:
    * action_dispatch.content_security_policy_nonce_generator :
    * action_dispatch.content_security_policy_report_only     : false
    * action_dispatch.cookies                                 : #<ActionDispatch::Cookies::CookieJar:0x00007f81cca69168>
    * action_dispatch.cookies_digest                          :
    * action_dispatch.cookies_rotations                       : #<ActiveSupport::Messages::RotationConfiguration:0x00005576618e3f28>
    * action_dispatch.cookies_same_site_protection            : #<Proc:0x0000557662a4cfd0@/var/www/violet/shared/bundle/ruby/2.6.0/gems/railties-6.1.5/lib/rails/application.rb:636>
    * action_dispatch.cookies_serializer                      : json
    * action_dispatch.encrypted_cookie_cipher                 : [FILTERED]
    * action_dispatch.encrypted_cookie_salt                   : [FILTERED]
    * action_dispatch.encrypted_signed_cookie_salt            : [FILTERED]
    * action_dispatch.http_auth_salt                          : [FILTERED]
    * action_dispatch.key_generator                           : #<ActiveSupport::CachingKeyGenerator:0x00005576656342d8>
    * action_dispatch.logger                                  : #<ActiveSupport::Logger:0x00005576637e41c0>
    * action_dispatch.parameter_filter                        : [:passw, :secret, :token, :_key, :crypt, :salt, :certificate, :otp, :ssn]
    * action_dispatch.permissions_policy                      :
    * action_dispatch.redirect_filter                         : []
    * action_dispatch.remote_ip                               : 142.188.123.103
    * action_dispatch.request.content_type                    :
    * action_dispatch.request.formats                         : [#<Mime::Type:0x0000557662435c28 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=-4436275399596115286>]
    * action_dispatch.request.parameters                      : {"q"=>{"properties_cont"=>"log"}, "commit"=>"Search", "controller"=>"comfy/admin/api_namespaces", "action"=>"index"}
    * action_dispatch.request.path_parameters                 : {:controller=>"comfy/admin/api_namespaces", :action=>"index"}
    * action_dispatch.request.query_parameters                : {"q"=>{"properties_cont"=>"log"}, "commit"=>"Search"}
    * action_dispatch.request.request_parameters              : {}
    * action_dispatch.request.unsigned_session_cookie         : {"session_id"=>"26e9b7f89827882fd4faf1c99d2f58d8", "user_return_to"=>"/api_namespaces", "warden.user.user.key"=>[[1], "$2a$12$WzLq2Z7gALlIsGWDuPTQQO"], "warden.user.user.session"=>{"last_request_at"=>1668283355}, "site_id"=>1, "_csrf_token"=>"[FILTERED]"}
    * action_dispatch.request_id                              : cd4fc114-6b46-4304-a7ce-b5996413032b
    * action_dispatch.routes                                  : #<ActionDispatch::Routing::RouteSet:0x000055766555f6f0>
    * action_dispatch.secret_key_base                         : [FILTERED]
    * action_dispatch.show_detailed_exceptions                : false
    * action_dispatch.show_exceptions                         : true
    * action_dispatch.signed_cookie_digest                    :
    * action_dispatch.signed_cookie_salt                      : [FILTERED]
    * action_dispatch.use_authenticated_cookie_encryption     : [FILTERED]
    * action_dispatch.use_cookies_with_metadata               : true
    * exception_notifier.exception_data                       : {:current_user=>#<User id: 1, global_admin: true, created_at: "2021-08-05 14:44:57.235323000 +0000", updated_at: "2022-11-12 20:02:11.557224000 +0000", email: "[contact@restarone.com](mailto:contact@restarone.com)", can_manage_web: true, can_manage_email: true, can_manage_users: true, can_manage_blog: true, name: "Shashike J", mod...
    * puma.config                                             : #<Puma::Configuration:0x0000557660bcb890>
    * puma.request_body_wait                                  : 0
    * puma.socket                                             : #<TCPSocket:0x00007f81cca1ebb8>
    * rack.after_reply                                        : []
    * rack.cors                                               : #<Rack::Cors::Result:0x00007f81cca1e0c8>
    * rack.errors                                             : #<IO:0x000055765fed80e8>
    * rack.hijack                                             : #<Puma::Client:0x00007f81cca1eb90>
    * rack.hijack?                                            : true
    * rack.input                                              : #<Puma::NullIO:0x00005576607c2fa0>
    * rack.multiprocess                                       : false
    * rack.multithread                                        : true
    * rack.request.cookie_hash                                : {"_r_solutions_session"=>"6/IoGAG/SYxgRdTg9xjOv4tm4s+K/ByQeFKgbOttnc9H1QDVFNkQcvzF0Gi76sotycq9Q2c79JH4DodT2PHTEwb2jhgm1l1nGr3GVgKMjK9kXYq0a30zKLHLyuCUUwJgEWDW+33vmsr3/RGhHppS/yRaUes6HmVVJ534+rlKPfcv8YcE8aKP8ZafG9u/zs4zUA9cidYE6MRszU33rJGYAgb/YC2s3Gkh+VDo4Fa/4/SLlWI+Os3xjp5jKD3kESuxdSKjU/Iav6vmYrlGvB...
    * rack.request.cookie_string                              : _r_solutions_session=6%2FIoGAG%2FSYxgRdTg9xjOv4tm4s%2BK%2FByQeFKgbOttnc9H1QDVFNkQcvzF0Gi76sotycq9Q2c79JH4DodT2PHTEwb2jhgm1l1nGr3GVgKMjK9kXYq0a30zKLHLyuCUUwJgEWDW%2B33vmsr3%2FRGhHppS%2FyRaUes6HmVVJ534%2BrlKPfcv8YcE8aKP8ZafG9u%2Fzs4zUA9cidYE6MRszU33rJGYAgb%2FYC2s3Gkh%2BVDo4Fa%2F4%2FSLlWI%2BOs3xjp5jKD3kESuxdSKjU%2FIav6vmYrlGvBaVv3NcBKHSl1boVpmZLzZBrbIVFeIRoZZcbO8h5ksDFq4xRE3n4Bj67PIVz7Y4fCvcOeW2xqjM740gKX4xsFb0ANOTt7GWFI30JDSprlKU7HRUVdFHTVLV6%2BxnYi9dpoc%2BVGIYZCWiRDwvzaEtC3d5a6E84IYbLPV2lIvQbsiX8D4xFAlFmfKwMmwtZgcpmxJ6Em9B1emyHb1F3XZ7Xj4fVJPNmsUDAU%2BU8ViLKKk4sLWb381tccECNiFiLpMYSNTVarTD2ftC3sblALxMWCYvGscEfgxjo55B%2B9AzDfoEbN2drwjclES%2B5yE%3D--Dr31oE2EL2CZ%2FzJo--YGEDbxtRyEwCFu0FZ%2FK3XQ%3D%3D; cookies_accepted=false
    * rack.request.query_hash                                 : {"q"=>{"properties_cont"=>"log"}, "commit"=>"Search"}
    * rack.request.query_string                               : q%5Bproperties_cont%5D=log&commit=Search
    * rack.run_once                                           : false
    * rack.session                                            : #<ActionDispatch::Request::Session:0x00007f81cca4e430>
    * rack.session.options                                    : #<ActionDispatch::Request::Session::Options:0x00007f81cca4e3e0>
    * rack.tempfiles                                          : []
    * rack.url_scheme                                         : https
    * rack.version                                            : [1, 6]
    * warden                                                  : Warden::Proxy:70097730433400 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[:rememberable, :database_authenticatable]}, :intercept_401=>false, :failure_app=>RSolutionsFailureApp}

-------------------------------
Backtrace:
-------------------------------

  app/helpers/application_helper.rb:8:in `page_entries_info'
  app/views/comfy/admin/api_namespaces/_pagination.haml:3
  app/views/comfy/admin/api_namespaces/index.html.haml:8

-------------------------------
Data:
-------------------------------

  * data: {:current_user=>
    #<User id: 1, global_admin: true, created_at: "2021-08-05 14:44:57.235323000 +0000", updated_at: "2022-11-12 20:02:11.557224000 +0000", email: "[contact@restarone.com](mailto:contact@restarone.com)", can_manage_web: true, can_manage_email: true, can_manage_users: true, can_manage_blog: true, name: "Shashike J", moderator: true, can_view_restricted_pages: true, deliver_analytics_report: true, can_manage_api: true, can_manage_subdomain_settings: true, session_timeoutable_in: "1-hour", can_access_admin: true, deliver_error_notifications: true, can_manage_analytics: true, can_manage_files: true>,
   :current_visit=>nil}
```

**Comment by alis-khadka** [comment]
@donrestarone 
Should we make the search filter to search by `name` or `properties` or both?

**Comment by donrestarone** [comment]
@alis-khadka let's make it searchable on both if it's not too hard. 

We need searchability on name for sure
