### ISSUE TITLE
enable turbo in /admin

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#1414]
**Is your feature request related to a problem? Please describe.**
currently turbo is not enabled in admin, causing the browser to open on mobile devices

**Describe the solution you'd like**
just like turbo works on the website and forum, it should work in admin

**Comment by donrestarone** [comment]
enable turbo in sign in, and make sure 2FA works: 

<img width="1713" alt="Screen Shot 2023-02-15 at 6 59 39 PM" src="https://user-images.githubusercontent.com/35935196/219222772-6124e4da-f646-471e-bd86-50d038f85783.png">

**Comment by donrestarone** [comment]
https://dev.to/ayushn21/http-redirects-in-a-turbo-rails-app-43jc

**Comment by donrestarone** [comment]
``` txt
solutions_app        | Started POST "/users/sign_in" for 172.28.0.1 at 2023-02-27 19:23:41 +0000                          
solutions_app        | source=rack-timeout id=0c13e32b-fc50-4a10-ab03-ad6cc95fda71 timeout=200000ms service=3ms state=acti
ve                                                                                                                        
solutions_app        |   Subdomain Load (0.5ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public".
"subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]                                                     
solutions_app        |   ↳ app/models/subdomain.rb:61:in `current'                                                        
solutions_app        |   Subdomain Load (0.5ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public".
"subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]                                                       
solutions_app        |   ↳ app/models/subdomain.rb:65:in `current'                                                        
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "pu
blic"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]                                               
solutions_app        |   ↳ app/models/subdomain.rb:61:in `current'                                                        
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "pu
blic"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]                                                 
solutions_app        |   ↳ app/models/subdomain.rb:65:in `current'                                                        
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "pu
blic"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]                                               
solutions_app        |   ↳ app/models/subdomain.rb:61:in `current'                                                        
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "pu
blic"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]                                                 
solutions_app        |   ↳ app/models/subdomain.rb:65:in `current'                                                        
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "pu
blic"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]                                               
solutions_app        |   ↳ app/models/subdomain.rb:61:in `current'                                                        
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "pu
blic"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]                                                 
solutions_app        |   ↳ app/models/subdomain.rb:65:in `current'                                                        
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "pu
blic"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]                                               
solutions_app        |   ↳ app/models/subdomain.rb:61:in `current'                                                        
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "pu
blic"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]                                                 
solutions_app        |   ↳ app/models/subdomain.rb:65:in `current'                                                        
solutions_app        | Cannot render console from 172.28.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1            
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "pu
blic"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]                                               
solutions_app        |   ↳ app/models/subdomain.rb:61:in `current'                                                        
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "pu
blic"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]                                                 
solutions_app        |   ↳ app/models/subdomain.rb:65:in `current'                                                        
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "pu
blic"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]                                               
solutions_app        |   ↳ app/models/subdomain.rb:61:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "pu
blic"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:65:in `current'
solutions_app        |   Subdomain Load (0.6ms)  SELECT "public"."subdomains".* FROM "public"."subdomains"
solutions_app        |   ↳ config/initializers/apartment.rb:54:in `each_with_object'
solutions_app        | Processing by Users::SessionsController#create as TURBO_STREAM
solutions_app        |   Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"violet@rails.com", "password"
=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Log in"}
solutions_app        |   User Load (1.1ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", 
"violet@rails.com"], ["LIMIT", 1]]
solutions_app        |   ↳ app/controllers/concerns/twofactor_authenticable.rb:69:in `find_user'
solutions_app        |   Subdomain Load (0.7ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public".
"subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:61:in `current'
solutions_app        |   Subdomain Load (0.7ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public".
"subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:65:in `current'
solutions_app        |   CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["em
ail", "violet@rails.com"], ["LIMIT", 1]]
solutions_app        |   ↳ app/controllers/concerns/twofactor_authenticable.rb:69:in `find_user'
solutions_app        | [ActiveJob] Enqueued ActionMailer::MailDeliveryJob (Job ID: 59403628-d2b9-411f-a78b-eafc66b76f3f) t
o Sidekiq(default) with arguments: "UserMailer", "send_otp", "deliver_now", {:args=>[#<GlobalID:0x0000ffff7dc84790 @uri=#<
URI::GID gid://r-solutions/User/1>>]}
solutions_sidekiq    | 2023-02-27T19:23:41.609Z pid=1 tid=1dvxl651rd class=ActionMailer::MailDeliveryJob jid=0e37ed83ac07a
c9e04072cde INFO: start
solutions_app        |   Rendering layout layouts/devise.html.haml
solutions_app        |   Rendering users/sessions/two_factor.html.erb within layouts/devise
solutions_app        |   Rendered users/sessions/two_factor.html.erb within layouts/devise (Duration: 4.1ms | Allocations:
 599)
```
