### ISSUE TITLE
undefined method `safe_raise' for Thread

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#1434]
``` txt
solutions_app        | source=rack-timeout id=0723d913-46b3-4d36-87df-032595b04765 timeout=5000ms state=ready
solutions_app        | source=rack-timeout id=fcb9ad7e-13fb-4287-b3a9-c005acda5fdf timeout=5000ms state=ready
solutions_app        | #<Thread:0x0000ffff98cd6778@/var/app/config/initializers/rack_timeout.rb:16 run> terminated with exception (report_on_exception is true):
solutions_app        | Traceback (most recent call last):
solutions_app        | /var/app/config/initializers/rack_timeout.rb:18:in `block in call': undefined method `safe_raise' for #<Thread:0x0000ffff955c58b0> (NoMethodError)
solutions_app        | #<Thread:0x0000ffff98cd5620@/var/app/config/initializers/rack_timeout.rb:16 run> terminated with exception (report_on_exception is true):
solutions_app        | Traceback (most recent call last):
solutions_app        | /var/app/config/initializers/rack_timeout.rb:18:in `block in call': undefined method `safe_raise' for #<Thread:0x0000ffff955c7d18> (NoMethodError)
solutions_app        | source=rack-timeout id=54c5962f-529b-42c0-a8f0-ecff775af98f timeout=5000ms service=5026ms state=active
solutions_app        | source=rack-timeout id=32a0f667-18d5-4aaf-bd32-81c09a76657c timeout=5000ms state=ready
solutions_app        | #<Thread:0x0000ffff98cd47c0@/var/app/config/initializers/rack_timeout.rb:16 run> terminated with exception (report_on_exception is true):
solutions_app        | Traceback (most recent call last):
solutions_app        | /var/app/config/initializers/rack_timeout.rb:18:in `block in call': undefined method `safe_raise' for #<Thread:0x0000ffff955aec00> (NoMethodError)
solutions_app        | source=rack-timeout id=0723d913-46b3-4d36-87df-032595b04765 timeout=5000ms state=ready
solutions_app        | source=rack-timeout id=54c5962f-529b-42c0-a8f0-ecff775af98f timeout=5000ms service=5031ms state=timed_out
solutions_app        | source=rack-timeout id=32a0f667-18d5-4aaf-bd32-81c09a76657c timeout=5000ms state=ready
```

**Comment by donrestarone** [comment]
this issue caused an outage on nikean.org today, 

``` txt
ubuntu@ip-172-31-14-250:~$ sudo systemctl status puma.service 
● puma.service - violet rails server
     Loaded: loaded (/etc/systemd/system/puma.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-03-10 16:04:09 UTC; 18min ago
   Main PID: 1022 (bundle)
      Tasks: 13 (limit: 2307)
     Memory: 367.9M
     CGroup: /system.slice/puma.service
             └─1022 puma 5.6.4 (tcp://0.0.0.0:3000) [20230226160309]

Mar 10 16:20:26 ip-172-31-14-250 rbenv[1022]: Did you mean?  safe_level
Mar 10 16:20:26 ip-172-31-14-250 rbenv[1022]: #<Thread:0x00007f1a997ad3b0@/var/www/violet/releases/20230226160309/config/initializers/rack_timeout.rb:16 run> terminated with exception (report_on_exception is true):
Mar 10 16:20:26 ip-172-31-14-250 rbenv[1022]: /var/www/violet/releases/20230226160309/config/initializers/rack_timeout.rb:18:in `block in call': undefined method `safe_raise' for #<Thread:0x0000557cefb86f20> (NoMethodError)
Mar 10 16:20:26 ip-172-31-14-250 rbenv[1022]: Did you mean?  safe_level
Mar 10 16:20:26 ip-172-31-14-250 rbenv[1022]: #<Thread:0x00007f1a94f87a18@/var/www/violet/releases/20230226160309/config/initializers/rack_timeout.rb:16 run> terminated with exception (report_on_exception is true):
Mar 10 16:20:26 ip-172-31-14-250 rbenv[1022]: /var/www/violet/releases/20230226160309/config/initializers/rack_timeout.rb:18:in `block in call': undefined method `safe_raise' for #<Thread:0x0000557cefc1c480> (NoMethodError)
Mar 10 16:20:26 ip-172-31-14-250 rbenv[1022]: Did you mean?  safe_level
Mar 10 16:22:07 ip-172-31-14-250 rbenv[1022]: #<Thread:0x00007f1a90756bb8@/var/www/violet/releases/20230226160309/config/initializers/rack_timeout.rb:16 run> terminated with exception (report_on_exception is true):
Mar 10 16:22:07 ip-172-31-14-250 rbenv[1022]: /var/www/violet/releases/20230226160309/config/initializers/rack_timeout.rb:18:in `block in call': undefined method `safe_raise' for #<Thread:0x0000557cefc1ca20> (NoMethodError)
Mar 10 16:22:07 ip-172-31-14-250 rbenv[1022]: Did you mean?  safe_level
```
