### ISSUE TITLE
PG::DivisionByZero error in analytics v2

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#1524]
**Describe the bug**

since https://github.com/restarone/violet_rails/releases/tag/0.9.110

``` txt
An ActiveRecord::StatementInvalid occurred in dashboard#dashboard:

  PG::DivisionByZero: ERROR:  division by zero

  app/models/ahoy/event.rb:129:in `avg_view_percentage_for_video_events'


-------------------------------
Request:
-------------------------------

  * URL        : https://nikean.org/v2/dashboard
  * HTTP Method: GET
  * IP address : 74.15.198.4
  * Parameters : {"controller"=>"comfy/admin/v2/dashboard", "action"=>"dashboard"}
  * Timestamp  : 2023-04-09 16:30:55 UTC
  * Server : ip-172-31-14-250
    * Rails root : /var/www/violet/releases/20230409162344
  * Process: 875409

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"",
   "user_return_to"=>"/v2/dashboard",
   "warden.user.user.key"=>[[1], "$2a"],
   "warden.user.user.session"=>{"last_request_at"=>err},
    * action_controller.instance                              : #<Comfy::Admin::V2::DashboardController:0x00007f1689662d70>
    * action_dispatch.authenticated_encrypted_cookie_salt     : [FILTERED]
    * action_dispatch.backtrace_cleaner                       : #<Rails::BacktraceCleaner:0x000055bf24f7e228>
    * action_dispatch.content_security_policy                 :
    * action_dispatch.content_security_policy_nonce_directives:
    * action_dispatch.content_security_policy_nonce_generator :
    * action_dispatch.content_security_policy_report_only     : false
    * action_dispatch.cookies                                 : #<ActionDispatch::Cookies::CookieJar:0x00007f1689672428>
    * action_dispatch.cookies_digest                          :
    * action_dispatch.cookies_rotations                       : #<ActiveSupport::Messages::RotationConfiguration:0x000055bf223b6348>
    * action_dispatch.cookies_same_site_protection            : #<Proc:0x000055bf26417180@/var/www/violet/shared/bundle/ruby/2.6.0/gems/railties-6.1.5/lib/rails/application.rb:636>
    * action_dispatch.cookies_serializer                      : json
    * action_dispatch.encrypted_cookie_cipher                 : [FILTERED]
    * action_dispatch.encrypted_cookie_salt                   : [FILTERED]
    * action_dispatch.encrypted_signed_cookie_salt            : [FILTERED]
    * action_dispatch.http_auth_salt                          : [FILTERED]
    * action_dispatch.key_generator                           : #<ActiveSupport::CachingKeyGenerator:0x000055bf26c89980>
    * action_dispatch.logger                                  : #<ActiveSupport::Logger:0x000055bf283c6bc0>
    * action_dispatch.parameter_filter                        : [:passw, :secret, :token, :_key, :crypt, :salt, :certificate, :otp, :ssn]
    * action_dispatch.permissions_policy                      :
    * action_dispatch.redirect_filter                         : []
    * action_dispatch.remote_ip                               : 74.15.198.4
    * action_dispatch.request.content_type                    :
    * action_dispatch.request.formats                         : [#<Mime::Type:0x000055bf238ed810 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=-3349831656498550952>]
    * action_dispatch.request.parameters                      : {"controller"=>"comfy/admin/v2/dashboard", "action"=>"dashboard"}
    * action_dispatch.request.path_parameters                 : {:controller=>"comfy/admin/v2/dashboard", :action=>"dashboard"}
    * action_dispatch.request.query_parameters                : {}
    * action_dispatch.request.request_parameters              : {}
    * action_dispatch.request.unsigned_session_cookie         : {"session_id"=>"359384bd7f35709ec57ca1a0a89887dd", "user_return_to"=>"/admin/sites/1/pages", "warden.user.user.key"=>[[1], "$2a$12$WzLq2Z7gALlIsGWDuPTQQO"], "warden.user.user.session"=>{"last_request_at"=>1681057855}, "site_id"=>1, "_csrf_token"=>"[FILTERED]"}
    * action_dispatch.request_id                              : c6b87615-2ab5-41bb-91f5-a76324f2bc4f
    * action_dispatch.routes                                  : #<ActionDispatch::Routing::RouteSet:0x000055bf27cccfe0>
    * action_dispatch.secret_key_base                         : [FILTERED]
    * action_dispatch.show_detailed_exceptions                : false
    * action_dispatch.show_exceptions                         : true
    * action_dispatch.signed_cookie_digest                    :
    * action_dispatch.signed_cookie_salt                      : [FILTERED]
    * action_dispatch.use_authenticated_cookie_encryption     : [FILTERED]
    * action_dispatch.use_cookies_with_metadata               : true
    * exception_notifier.exception_data                       : {:current_user=>#<User id: 1, global_admin: true, created_at: "2021-08-05 14:44:57.235323000 +0000", updated_at: "2023-04-09 16:30:51.342099000 +0000", email: "[contact@restarone.com](mailto:contact@restarone.com)", can_manage_web: true, can_manage_email: true, can_manage_users: true, can_manage_blog: true, name: "Shashike J", mod...
    * puma.config                                             : #<Puma::Configuration:0x000055bf21cc64e8>
    * puma.request_body_wait                                  : 0
    * puma.socket                                             : #<TCPSocket:0x00007f168962cec8>
    * [rack-timeout.info](http://rack-timeout.info/)                                       : #<struct Rack::Timeout::RequestDetails id="c6b87615-2ab5-41bb-91f5-a76324f2bc4f", wait=nil, service=0.00010682700667530298, timeout=15, state=:active, term=false>
    * rack.after_reply                                        : []
    * rack.cors                                               : #<Rack::Cors::Result:0x00007f1689632d50>
    * rack.errors                                             : #<IO:0x000055bf210440d0>
    * rack.hijack                                             : #<Puma::Client:0x00007f168962cea0>
    * rack.hijack?                                            : true
    * rack.input                                              : #<Puma::NullIO:0x000055bf21b56ea0>
    * rack.multiprocess                                       : false
    * rack.multithread                                        : true
    * rack.request.cookie_hash                                : {"__profilin"=>"p=t,a=f5f48a6ecf89d13cfd3279edf0b4c299", "_r_solutions_session"=>"kZ7XpCulWvgmGee9ouesw9bTDo2ou0ON0Zf0rw48C9KB4uKFpYQz2vimwWmCHeYQoshAUbkjKQYhvkrIuRhELQMohGVHK2uCNutsP5KYFsTizYoL+mgj81wBxusf67ZrpOqYC/VKYPKAZpIbILm/hqGUJMMCS0NBEiAr0yhJL9pr5vqgQBCcm6SoEVMV8iY9mqMM0j3uCR29H3qnbN/ITJVwJw...
    * rack.request.cookie_string                              : __profilin=p%3Dt%2Ca%3Df5f48a6ecf89d13cfd3279edf0b4c299; _r_solutions_session=kZ7XpCulWvgmGee9ouesw9bTDo2ou0ON0Zf0rw48C9KB4uKFpYQz2vimwWmCHeYQoshAUbkjKQYhvkrIuRhELQMohGVHK2uCNutsP5KYFsTizYoL%2Bmgj81wBxusf67ZrpOqYC%2FVKYPKAZpIbILm%2FhqGUJMMCS0NBEiAr0yhJL9pr5vqgQBCcm6SoEVMV8iY9mqMM0j3uCR29H3qnbN%2FITJVwJwqvAqHuxqPtp6IMrsmDPJeeL2AY4KtCkwdomBZupkmr3nYWoDdK5t%2BTMBvAv5gF3M0PSFma1Hx4%2FpFoJn%2BPI6JGzaNgFqPg3gl1rSjDyB8eZYM%2FsrPSBeRJ%2B3a%2BOY9ruaz811xD9qiU1baGG5jPHW5nLuhv2DuBPbmDRHUNeQ91EKPiAb9ql%2BYfzB35Xgdwl1JfbNJnrStWalXWQEugPiFndZRQ9PI%2FhBXOgcZ7KsPtfu%2Fs6%2B9EHw%2BpjZJT0E%2F3F7gEiuGRxNT2bMJf9oeHf3GeDSLtVrO8OIFGOKmVTt82%2B23KuMCrnLK7hCuAxrEAviUmGiRmd3Ofg0sKNRkyWVXsICkCd2ug0uHnJN3GfLpx3%2BHrVRDr7an20d6jvg%3D%3D--IIVi59nTi5T%2BJxnI--xwGEFnAKZTKSEZjweHieHA%3D%3D; cookies_accepted=false
    * rack.request.query_hash                                 : {}
    * rack.request.query_string                               :
    * rack.run_once                                           : false
    * rack.session                                            : #<ActionDispatch::Request::Session:0x00007f1689656d40>
    * rack.session.options                                    : #<ActionDispatch::Request::Session::Options:0x00007f1689656cf0>
    * rack.tempfiles                                          : []
    * rack.url_scheme                                         : https
    * rack.version                                            : [1, 6]
    * warden                                                  : Warden::Proxy:69867385566720 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[:two_factor_authenticatable, :two_factor_authenticatable, :rememberable]}, :intercept_401=>false, :failure_app=>RSolutionsFailureApp}



-------------------------------
Backtrace:
-------------------------------

  app/models/ahoy/event.rb:129:in `avg_view_percentage_for_video_events'
  app/controllers/comfy/admin/v2/dashboard_controller.rb:48:in `block in set_event_category_specific_analytics_data'
  app/controllers/comfy/admin/v2/dashboard_controller.rb:16:in `each'
  app/controllers/comfy/admin/v2/dashboard_controller.rb:16:in `set_event_category_specific_analytics_data'
  app/controllers/comfy/admin/v2/dashboard_controller.rb:10:in `dashboard'

-------------------------------
Data:
-------------------------------

  * data: {:current_user=>
    #<User id: 1, global_admin: true, created_at: "2021-08-05 14:44:57.235323000 +0000", updated_at: "2023-04-09 16:30:51.342099000 +0000", email: "[contact@restarone.com](mailto:contact@restarone.com)", can_manage_web: true, can_manage_email: true, can_manage_users: true, can_manage_blog: true, name: "Shashike J", moderator: true, can_view_restricted_pages: true, deliver_analytics_report: true, can_manage_subdomain_settings: true, session_timeoutable_in: "1-hour", can_access_admin: true, deliver_error_notifications: true, can_manage_analytics: true, can_manage_files: true, encrypted_otp_secret: nil, encrypted_otp_secret_iv: nil, encrypted_otp_secret_salt: nil, consumed_timestep: nil, otp_required_for_login: false, api_accessibility: {"api_keys"=>{"full_access"=>"true"}, "api_namespaces"=>{"all_namespaces"=>{"full_access"=>"true"}}}, can_access_forum: true, show_profiler: true, otp_secret: nil>,
   :current_visit=>nil}
```

**Comment by donrestarone** [comment]
there is a gap in the test suite. We need to add a test that detects issues with video analytics (to address the breakages in nikean.org)
