### ISSUE TITLE
".tooltip is not a function" in analytics v2

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#1609]
**Describe the bug**

**To Reproduce**
1. Go to https://markedrestaurant.com/v2/dashboard
2. see date range picker is broken
3. see error in console

``` txt
Error initializing controller

TypeError: e(...).tooltip is not a function
    at t.value (dashboard_controller.js:7:34)
    at new e (stimulus.js:2331:23)
    at e.value (stimulus.js:2622:19)
    at e.value (stimulus.js:2602:26)
    at e.value (stimulus.js:3222:16)
    at e.value (stimulus.js:3088:23)
    at e.value (stimulus.js:1594:23)
    at e.value (stimulus.js:1478:21)
    at stimulus.js:1463:23
    at Array.forEach (<anonymous>)
```

![Screenshot from 2023-09-18 16-32-56](https://github.com/restarone/violet_rails/assets/35935196/b0d8179d-d55b-4fa6-8671-678d7c209f56)

**Comment by donrestarone** [comment]
last known commit when the view was functional: 66a63e4448624bafbadf17cf503e6added58a9dc
