### ISSUE TITLE
[Data pipelines] unknown attribute preview_content when CMS page is updated

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#254]
@Pralish Just deployed data pipelines to staging, https://github.com/restarone/violet_rails/pull/236 and noticed the following error when I update any page: 

``` bash
I, [2021-11-18T13:49:27.215212 #654898]  INFO -- : [ee9fae62-963b-446c-9ab1-ce91d2fa820a] Started PATCH "/admin/sites/1/pages/5" for 184.146.52.234 at 2021-11-18 13:49:27 +0000
D, [2021-11-18T13:49:27.217619 #654898] DEBUG -- : [ee9fae62-963b-446c-9ab1-ce91d2fa820a]   Subdomain Load (1.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains"
I, [2021-11-18T13:49:27.221170 #654898]  INFO -- : [ee9fae62-963b-446c-9ab1-ce91d2fa820a] Processing by Comfy::Admin::Cms::PagesController#update as HTML
I, [2021-11-18T13:49:27.221280 #654898]  INFO -- : [ee9fae62-963b-446c-9ab1-ce91d2fa820a]   Parameters: {"authenticity_token"=>"[FILTERED]", "page"=>{"label"=>"newsletter", "slug"=>"newsletter", "parent_id"=>"1", "layout_id"=>"1", "is_restricted"=>"1", "preview_content"=>"", "fragments_attributes"=>{"0"=>{"identifier"=>"content", "tag"=>"wysiwyg", "content"=>"<div class=\"container\">\r\n\t{{ cms:snippet collect-email-address }}\r\n</div><div class=\"container\">\r\n\t{{ cms:snippet contact-form }}\r\n</div>"}}, "target_page_id"=>"", "is_published"=>"1"}, "commit"=>"Update Page", "site_id"=>"1", "id"=>"5"}
D, [2021-11-18T13:49:27.223502 #654898] DEBUG -- : [ee9fae62-963b-446c-9ab1-ce91d2fa820a]   User Load (0.9ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
D, [2021-11-18T13:49:27.225105 #654898] DEBUG -- : [ee9fae62-963b-446c-9ab1-ce91d2fa820a]   User Load (0.8ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
D, [2021-11-18T13:49:27.226624 #654898] DEBUG -- : [ee9fae62-963b-446c-9ab1-ce91d2fa820a]   Comfy::Cms::Site Load (0.7ms)  SELECT "comfy_cms_sites".* FROM "comfy_cms_sites" WHERE "comfy_cms_sites"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
D, [2021-11-18T13:49:27.228599 #654898] DEBUG -- : [ee9fae62-963b-446c-9ab1-ce91d2fa820a]   Comfy::Cms::Page Load (0.9ms)  SELECT "comfy_cms_pages".* FROM "comfy_cms_pages" WHERE "comfy_cms_pages"."site_id" = $1 AND "comfy_cms_pages"."id" = $2 LIMIT $3  [["site_id", 1], ["id", 5], ["LIMIT", 1]]
D, [2021-11-18T13:49:27.230126 #654898] DEBUG -- : [ee9fae62-963b-446c-9ab1-ce91d2fa820a]   Comfy::Cms::Page Load (0.9ms)  SELECT "comfy_cms_pages".* FROM "comfy_cms_pages" WHERE "comfy_cms_pages"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
I, [2021-11-18T13:49:27.230686 #654898]  INFO -- : [ee9fae62-963b-446c-9ab1-ce91d2fa820a] Completed 500 Internal Server Error in 9ms (ActiveRecord: 4.2ms | Allocations: 1941)
F, [2021-11-18T13:49:27.232851 #654898] FATAL -- : [ee9fae62-963b-446c-9ab1-ce91d2fa820a]
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] ActiveModel::UnknownAttributeError (unknown attribute 'preview_content' for Comfy::Cms::Page.):
[ee9fae62-963b-446c-9ab1-ce91d2fa820a]
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activemodel (6.1.3.1) lib/active_model/attribute_assignment.rb:51:in `_assign_attribute'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activerecord (6.1.3.1) lib/active_record/attribute_assignment.rb:21:in `block in _assign_attributes'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activerecord (6.1.3.1) lib/active_record/attribute_assignment.rb:13:in `each'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activerecord (6.1.3.1) lib/active_record/attribute_assignment.rb:13:in `_assign_attributes'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activemodel (6.1.3.1) lib/active_model/attribute_assignment.rb:34:in `assign_attributes'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] comfortable-mexican-sofa (31a984419bc0) app/controllers/comfy/admin/cms/pages_controller.rb:128:in `load_page'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activesupport (6.1.3.1) lib/active_support/callbacks.rb:427:in `block in make_lambda'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activesupport (6.1.3.1) lib/active_support/callbacks.rb:179:in `block (2 levels) in halting_and_conditional'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activesupport (6.1.3.1) lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activesupport (6.1.3.1) lib/active_support/callbacks.rb:512:in `block in invoke_before'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activesupport (6.1.3.1) lib/active_support/callbacks.rb:512:in `each'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activesupport (6.1.3.1) lib/active_support/callbacks.rb:512:in `invoke_before'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activesupport (6.1.3.1) lib/active_support/callbacks.rb:115:in `block in run_callbacks'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] ahoy_matey (3.2.0) lib/ahoy/controller.rb:45:in `set_ahoy_request_store'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activesupport (6.1.3.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actiontext (6.1.3.1) lib/action_text/rendering.rb:20:in `with_renderer'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actiontext (6.1.3.1) lib/action_text/engine.rb:55:in `block (4 levels) in <class:Engine>'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activesupport (6.1.3.1) lib/active_support/callbacks.rb:126:in `instance_exec'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activesupport (6.1.3.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activesupport (6.1.3.1) lib/active_support/callbacks.rb:137:in `run_callbacks'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `block in instrument'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activesupport (6.1.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `instrument'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activerecord (6.1.3.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/abstract_controller/base.rb:165:in `process'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionview (6.1.3.1) lib/action_view/rendering.rb:39:in `process'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_controller/metal.rb:190:in `dispatch'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_controller/metal.rb:254:in `dispatch'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `each'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:842:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] ros-apartment (2.9.0) lib/apartment/elevators/generic.rb:22:in `block in call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] ros-apartment (2.9.0) lib/apartment/adapters/abstract_adapter.rb:89:in `switch'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] /home/ubuntu/.rbenv/versions/2.6.6/lib/ruby/2.6.0/forwardable.rb:230:in `switch'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] ros-apartment (2.9.0) lib/apartment/elevators/generic.rb:22:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] warden (1.2.9) lib/warden/manager.rb:34:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] rack (2.2.3) lib/rack/etag.rb:27:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] rack (2.2.3) lib/rack/head.rb:12:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_dispatch/middleware/cookies.rb:689:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activesupport (6.1.3.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] railties (6.1.3.1) lib/rails/rack/logger.rb:37:in `call_app'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] railties (6.1.3.1) lib/rails/rack/logger.rb:26:in `block in call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:99:in `block in tagged'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:37:in `tagged'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:99:in `tagged'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] railties (6.1.3.1) lib/rails/rack/logger.rb:26:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] ahoy_matey (3.2.0) lib/ahoy/engine.rb:22:in `call_with_quiet_ahoy'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] rack (2.2.3) lib/rack/method_override.rb:24:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] activesupport (6.1.3.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_dispatch/middleware/static.rb:24:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] actionpack (6.1.3.1) lib/action_dispatch/middleware/host_authorization.rb:92:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] railties (6.1.3.1) lib/rails/engine.rb:539:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] puma (5.2.2) lib/puma/configuration.rb:248:in `call'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] puma (5.2.2) lib/puma/request.rb:76:in `block in handle_request'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] puma (5.2.2) lib/puma/thread_pool.rb:337:in `with_force_shutdown'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] puma (5.2.2) lib/puma/request.rb:75:in `handle_request'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] puma (5.2.2) lib/puma/server.rb:431:in `process_client'
[ee9fae62-963b-446c-9ab1-ce91d2fa820a] puma (5.2.2) lib/puma/thread_pool.rb:145:in `block in spawn_thread'

```

**Comment by donrestarone** [comment]
Just making sure we have everything lined up: 

1. we added a preview_content column to the CMS (db/migrate/20210823235033_add_preview_to_cms_pages.rb)
2. The CMS allows for all attributes through the controller (app/controllers/comfy/admin/cms/pages_controller.rb)
3. We see that the column is recognized in the rails console: 
``` ruby
irb(main):001:0> Comfy::Cms::Page.first
  Comfy::Cms::Page Load (1.8ms)  SELECT "comfy_cms_pages".* FROM "comfy_cms_pages" ORDER BY "comfy_cms_pages"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> #<Comfy::Cms::Page id: 1, site_id: 1, layout_id: 1, parent_id: nil, target_page_id: nil, label: "root", slug: nil, full_path: "/", content_cache: "<div class=\"jumbotron container\">\r\n\t<h1 class=\"dis...", position: 0, children_count: 0, is_published: true, created_at: "2021-05-19 13:06:11.934109000 +0000", updated_at: "2021-05-19 15:30:55.999737000 +0000", is_restricted: nil, preview_content: nil>
irb(main):002:0> Comfy::Cms::Page.first.preview_content
  Comfy::Cms::Page Load (1.2ms)  SELECT "comfy_cms_pages".* FROM "comfy_cms_pages" ORDER BY "comfy_cms_pages"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> nil
irb(main):003:0>
```

**Comment by donrestarone** [comment]
I fixed this by manually creating the column. But we should investigate why this happened. There is an entry for creating this column in the `schema_migrations` table but the actual column was not created anymore except for in the `public` schema
