### ISSUE TITLE
cannot create a page in CMS

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#340]
ENV: violet.restarone.solutions
version: Branch master (at cbf3ed2a6228ef6706a5b45796e501b56211b523) deployed as release 20220328233741 by runner

``` txt

I, [2022-03-31T20:14:01.915940 #587264]  INFO -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885] Started POST "/admin/sites/1/pages" for 184.146.52.234 at 2022-03-31 20:14:01 +0000
D, [2022-03-31T20:14:01.918509 #587264] DEBUG -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885]   Subdomain Load (1.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains"
I, [2022-03-31T20:14:01.921714 #587264]  INFO -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885] Processing by Comfy::Admin::Cms::PagesController#create as HTML
I, [2022-03-31T20:14:01.921832 #587264]  INFO -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885]   Parameters: {"authenticity_token"=>"[FILTERED]", "page"=>{"label"=>"rrr", "slug"=>"rrr", "parent_id"=>"1", "layout_id"=>"1", "is_restricted"=>"0", "preview_content"=>"", "fragments_attributes"=>{"0"=>{"identifier"=>"content", "tag"=>"wysiwyg", "content"=>""}}, "target_page_id"=>"", "is_published"=>"1"}, "commit"=>"Create Page", "site_id"=>"1"}
D, [2022-03-31T20:14:01.924118 #587264] DEBUG -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885]   User Load (0.9ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
D, [2022-03-31T20:14:01.926287 #587264] DEBUG -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885]   User Load (0.9ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
D, [2022-03-31T20:14:01.931917 #587264] DEBUG -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885]   Comfy::Cms::Site Load (0.9ms)  SELECT "comfy_cms_sites".* FROM "comfy_cms_sites" WHERE "comfy_cms_sites"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
D, [2022-03-31T20:14:01.933967 #587264] DEBUG -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885]   Comfy::Cms::Page Load (1.0ms)  SELECT "comfy_cms_pages".* FROM "comfy_cms_pages" WHERE "comfy_cms_pages"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
D, [2022-03-31T20:14:01.937823 #587264] DEBUG -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885]   Comfy::Cms::Layout Load (2.0ms)  SELECT "comfy_cms_layouts".* FROM "comfy_cms_layouts" WHERE "comfy_cms_layouts"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
D, [2022-03-31T20:14:01.942846 #587264] DEBUG -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885]   TRANSACTION (0.8ms)  BEGIN
D, [2022-03-31T20:14:01.944232 #587264] DEBUG -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885]   Comfy::Cms::Page Load (1.1ms)  SELECT "comfy_cms_pages".* FROM "comfy_cms_pages" WHERE "comfy_cms_pages"."site_id" = $1 AND (parent_id IS NULL) ORDER BY position LIMIT $2  [["site_id", 1], ["LIMIT", 1]]
D, [2022-03-31T20:14:01.946024 #587264] DEBUG -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885]    (0.8ms)  SELECT COUNT(*) FROM "comfy_cms_pages" WHERE "comfy_cms_pages"."site_id" = $1  [["site_id", 1]]
D, [2022-03-31T20:14:01.947982 #587264] DEBUG -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885]   Comfy::Cms::Fragment Exists? (0.8ms)  SELECT 1 AS one FROM "comfy_cms_fragments" WHERE "comfy_cms_fragments"."identifier" = $1 AND "comfy_cms_fragments"."record_type" = $2 AND "comfy_cms_fragments"."record_id" IS NULL LIMIT $3  [["identifier", "content"], ["record_type", "Comfy::Cms::Page"], ["LIMIT", 1]]
D, [2022-03-31T20:14:01.948947 #587264] DEBUG -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885]   CACHE  (0.0ms)  SELECT COUNT(*) FROM "comfy_cms_pages" WHERE "comfy_cms_pages"."site_id" = $1  [["site_id", 1]]
D, [2022-03-31T20:14:01.950047 #587264] DEBUG -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885]   CACHE Comfy::Cms::Page Load (0.0ms)  SELECT "comfy_cms_pages".* FROM "comfy_cms_pages" WHERE "comfy_cms_pages"."site_id" = $1 AND (parent_id IS NULL) ORDER BY position LIMIT $2  [["site_id", 1], ["LIMIT", 1]]
D, [2022-03-31T20:14:01.951627 #587264] DEBUG -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885]   CACHE  (0.0ms)  SELECT COUNT(*) FROM "comfy_cms_pages" WHERE "comfy_cms_pages"."site_id" = $1  [["site_id", 1]]
D, [2022-03-31T20:14:01.956241 #587264] DEBUG -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885]   CACHE Comfy::Cms::Page Load (0.0ms)  SELECT "comfy_cms_pages".* FROM "comfy_cms_pages" WHERE "comfy_cms_pages"."site_id" = $1 AND (parent_id IS NULL) ORDER BY position LIMIT $2  [["site_id", 1], ["LIMIT", 1]]
D, [2022-03-31T20:14:01.958321 #587264] DEBUG -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885]   Comfy::Cms::Page Exists? (1.1ms)  SELECT 1 AS one FROM "comfy_cms_pages" WHERE "comfy_cms_pages"."slug" = $1 AND "comfy_cms_pages"."parent_id" = $2 LIMIT $3  [["slug", "rrr"], ["parent_id", 1], ["LIMIT", 1]]
D, [2022-03-31T20:14:01.961958 #587264] DEBUG -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885]    (2.2ms)  SELECT MAX("comfy_cms_pages"."position") FROM "comfy_cms_pages" WHERE "comfy_cms_pages"."parent_id" = $1  [["parent_id", 1]]
D, [2022-03-31T20:14:01.965144 #587264] DEBUG -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885]   Comfy::Cms::Page Create (1.1ms)  INSERT INTO "comfy_cms_pages" ("site_id", "layout_id", "parent_id", "label", "slug", "full_path", "created_at", "updated_at", "is_restricted", "preview_content") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"  [["site_id", 1], ["layout_id", 1], ["parent_id", 1], ["label", "rrr"], ["slug", "rrr"], ["full_path", "/rrr"], ["created_at", "2022-03-31 20:14:01.958778"], ["updated_at", "2022-03-31 20:14:01.958778"], ["is_restricted", false], ["preview_content", ""]]
D, [2022-03-31T20:14:01.966047 #587264] DEBUG -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885]   TRANSACTION (0.7ms)  ROLLBACK
I, [2022-03-31T20:14:01.966383 #587264]  INFO -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885] Completed 500 Internal Server Error in 44ms (ActiveRecord: 14.4ms | Allocations: 5317)
F, [2022-03-31T20:14:01.969972 #587264] FATAL -- : [d6d3b566-e0f7-4e05-a1a0-61ae6c004885]
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column "preview_content" of relation "comfy_cms_pages" does not exist
LINE 1: ...th", "created_at", "updated_at", "is_restricted", "preview_c...
                                                             ^
):
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885]
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `exec_params'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `block (2 levels) in exec_no_cache'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `block in exec_no_cache'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/connection_adapters/postgresql_adapter.rb:670:in `exec_no_cache'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/connection_adapters/postgresql_adapter.rb:649:in `execute_and_clear'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:53:in `exec_query'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/connection_adapters/abstract/database_statements.rb:136:in `exec_insert'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:91:in `exec_insert'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/connection_adapters/abstract/database_statements.rb:171:in `insert'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `insert'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/persistence.rb:375:in `_insert_record'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/persistence.rb:929:in `_create_record'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/counter_cache.rb:166:in `_create_record'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/locking/optimistic.rb:79:in `_create_record'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/attribute_methods/dirty.rb:201:in `_create_record'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/callbacks.rb:461:in `block in _create_record'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/callbacks.rb:106:in `run_callbacks'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/callbacks.rb:824:in `_run_create_callbacks'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/callbacks.rb:461:in `_create_record'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/timestamp.rb:108:in `_create_record'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/persistence.rb:900:in `create_or_update'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/callbacks.rb:457:in `block in create_or_update'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/autosave_association.rb:385:in `around_save_collection_association'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/callbacks.rb:137:in `run_callbacks'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/callbacks.rb:824:in `_run_save_callbacks'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/callbacks.rb:457:in `create_or_update'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/timestamp.rb:126:in `create_or_update'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/persistence.rb:507:in `save!'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/validations.rb:53:in `save!'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/transactions.rb:302:in `block in save!'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/connection_adapters/abstract/transaction.rb:310:in `block in within_new_transaction'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/connection_adapters/abstract/transaction.rb:308:in `within_new_transaction'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/transactions.rb:302:in `save!'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/suppressor.rb:48:in `save!'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] comfortable-mexican-sofa (2b80ce723ce9) app/controllers/comfy/admin/cms/pages_controller.rb:40:in `create'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/abstract_controller/base.rb:228:in `process_action'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] ahoy_matey (3.2.0) lib/ahoy/controller.rb:45:in `set_ahoy_request_store'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actiontext (6.1.3.1) lib/action_text/rendering.rb:20:in `with_renderer'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actiontext (6.1.3.1) lib/action_text/engine.rb:55:in `block (4 levels) in <class:Engine>'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/callbacks.rb:126:in `instance_exec'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/callbacks.rb:137:in `run_callbacks'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `block in instrument'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `instrument'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activerecord (6.1.3.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/abstract_controller/base.rb:165:in `process'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionview (6.1.3.1) lib/action_view/rendering.rb:39:in `process'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_controller/metal.rb:190:in `dispatch'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_controller/metal.rb:254:in `dispatch'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `each'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:842:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] ros-apartment (2.9.0) lib/apartment/elevators/generic.rb:22:in `block in call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] ros-apartment (2.9.0) lib/apartment/adapters/abstract_adapter.rb:89:in `switch'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] /home/ubuntu/.rbenv/versions/2.6.6/lib/ruby/2.6.0/forwardable.rb:230:in `switch'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] ros-apartment (2.9.0) lib/apartment/elevators/generic.rb:22:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] warden (1.2.9) lib/warden/manager.rb:34:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] rack (2.2.3) lib/rack/etag.rb:27:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] rack (2.2.3) lib/rack/head.rb:12:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_dispatch/middleware/cookies.rb:689:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] railties (6.1.3.1) lib/rails/rack/logger.rb:37:in `call_app'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] railties (6.1.3.1) lib/rails/rack/logger.rb:26:in `block in call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:99:in `block in tagged'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:37:in `tagged'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:99:in `tagged'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] railties (6.1.3.1) lib/rails/rack/logger.rb:26:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] ahoy_matey (3.2.0) lib/ahoy/engine.rb:22:in `call_with_quiet_ahoy'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] rack (2.2.3) lib/rack/method_override.rb:24:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] activesupport (6.1.3.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_dispatch/middleware/static.rb:24:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] actionpack (6.1.3.1) lib/action_dispatch/middleware/host_authorization.rb:92:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] railties (6.1.3.1) lib/rails/engine.rb:539:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] puma (5.3.1) lib/puma/configuration.rb:249:in `call'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] puma (5.3.1) lib/puma/request.rb:76:in `block in handle_request'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] puma (5.3.1) lib/puma/thread_pool.rb:338:in `with_force_shutdown'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] puma (5.3.1) lib/puma/request.rb:75:in `handle_request'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] puma (5.3.1) lib/puma/server.rb:437:in `process_client'
[d6d3b566-e0f7-4e05-a1a0-61ae6c004885] puma (5.3.1) lib/puma/thread_pool.rb:145:in `block in spawn_thread'


```

**Comment by donrestarone** [comment]
fix was to:

``` sql
ALTER TABLE sandbox.comfy_cms_pages
    ADD COLUMN preview_content text COLLATE pg_catalog."default";
```
