### ISSUE TITLE
forum email notification is not sent when file is attached (variant 2)

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#422]
``` txt
I, [2022-04-20T02:28:23.982865 #7618]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [d3d5abb5-d1fb-476a-8809-288fa0e49153] Performing ActionMailer::MailDeliveryJob (Job ID: d3d5abb5-d1fb-476a-8809-288fa0e49153) from Sidekiq(default) enqueued at 2022-04-18T16:42:42Z with arguments: "SimpleDiscussion::UserMailer", "new_post", "deliver_now", {:args=>[#<GlobalID:0x00007f9cb0a9ade0 @uri=#<URI::GID gid://r-solutions/ForumPost/18>>, #<GlobalID:0x00007f9cb0a9a750 @uri=#<URI::GID gid://r-solutions/User/1>>]}
D, [2022-04-20T02:28:23.984593 #7618] DEBUG -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [d3d5abb5-d1fb-476a-8809-288fa0e49153]   ForumThread Load (0.7ms)  SELECT "forum_threads".* FROM "forum_threads" WHERE "forum_threads"."id" = $1 LIMIT $2  [["id", 3], ["LIMIT", 1]]
D, [2022-04-20T02:28:23.985488 #7618] DEBUG -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [d3d5abb5-d1fb-476a-8809-288fa0e49153]   Rendering simple_discussion/user_mailer/new_post.html.haml
D, [2022-04-20T02:28:23.987031 #7618] DEBUG -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [d3d5abb5-d1fb-476a-8809-288fa0e49153]   User Load (0.9ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
D, [2022-04-20T02:28:23.989111 #7618] DEBUG -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [d3d5abb5-d1fb-476a-8809-288fa0e49153]   ActionText::RichText Load (0.8ms)  SELECT "action_text_rich_texts".* FROM "action_text_rich_texts" WHERE "action_text_rich_texts"."record_id" = $1 AND "action_text_rich_texts"."record_type" = $2 AND "action_text_rich_texts"."name" = $3 LIMIT $4  [["record_id", 18], ["record_type", "ForumPost"], ["name", "body"], ["LIMIT", 1]]
D, [2022-04-20T02:28:23.992001 #7618] DEBUG -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [d3d5abb5-d1fb-476a-8809-288fa0e49153]   ActiveStorage::Blob Load (0.9ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 22], ["LIMIT", 1]]
D, [2022-04-20T02:28:23.994476 #7618] DEBUG -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [d3d5abb5-d1fb-476a-8809-288fa0e49153]   Rendered active_storage/blobs/_blob.html.erb (Duration: 1.6ms | Allocations: 2457)
D, [2022-04-20T02:28:23.994625 #7618] DEBUG -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [d3d5abb5-d1fb-476a-8809-288fa0e49153]   Rendered /var/www/violet/shared/bundle/ruby/2.6.0/gems/actiontext-6.1.5/app/views/action_text/content/_layout.html.erb (Duration: 4.4ms | Allocations: 3856)
I, [2022-04-20T02:28:23.994808 #7618]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [d3d5abb5-d1fb-476a-8809-288fa0e49153]   Rendered simple_discussion/user_mailer/new_post.html.haml (Duration: 9.1ms | Allocations: 5095)
D, [2022-04-20T02:28:23.995022 #7618] DEBUG -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [d3d5abb5-d1fb-476a-8809-288fa0e49153] SimpleDiscussion::UserMailer#new_post: processed outbound mail in 11.7ms
E, [2022-04-20T02:28:23.995432 #7618] ERROR -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [d3d5abb5-d1fb-476a-8809-288fa0e49153] Error performing ActionMailer::MailDeliveryJob (Job ID: d3d5abb5-d1fb-476a-8809-288fa0e49153) from Sidekiq(default) in 12.1ms: ActionView::Template::Error (Can't resolve image into URL: undefined method `to_model' for #<ActiveStorage::VariantWithRecord:0x00007f9cacca7128>
Did you mean?  to_yaml):
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actionview-6.1.5/lib/action_view/helpers/asset_tag_helper.rb:487:in `rescue in resolve_image_source'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actionview-6.1.5/lib/action_view/helpers/asset_tag_helper.rb:480:in `resolve_image_source'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actionview-6.1.5/lib/action_view/helpers/asset_tag_helper.rb:375:in `image_tag'
/var/www/violet/releases/20220419211037/app/views/active_storage/blobs/_blob.html.erb:3:in `_app_views_active_storage_blobs__blob_html_erb___1611660934410372500_47346901533800'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actionview-6.1.5/lib/action_view/base.rb:247:in `public_send'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actionview-6.1.5/lib/action_view/base.rb:247:in `_run'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actionview-6.1.5/lib/action_view/template.rb:154:in `block in render'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.5/lib/active_support/notifications.rb:205:in `instrument'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actionview-6.1.5/lib/action_view/template.rb:345:in `instrument_render_template'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actionview-6.1.5/lib/action_view/template.rb:152:in `render'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actionview-6.1.5/lib/action_view/renderer/partial_renderer.rb:285:in `block in render_partial_template'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.5/lib/active_support/notifications.rb:203:in `block in instrument'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.5/lib/active_support/notifications.rb:203:in `instrument'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actionview-6.1.5/lib/action_view/renderer/partial_renderer.rb:280:in `render_partial_template'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actionview-6.1.5/lib/action_view/renderer/object_renderer.rb:31:in `render_partial_template'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actionview-6.1.5/lib/action_view/renderer/partial_renderer.rb:271:in `render'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actionview-6.1.5/lib/action_view/renderer/object_renderer.rb:16:in `render_object_with_partial'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actionview-6.1.5/lib/action_view/renderer/object_renderer.rb:21:in `render_object_derive_partial'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actionview-6.1.5/lib/action_view/renderer/renderer.rb:94:in `render_partial_to_object'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actionview-6.1.5/lib/action_view/renderer/renderer.rb:53:in `render_partial'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actionview-6.1.5/lib/action_view/helpers/rendering_helper.rb:45:in `render'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/haml-5.2.2/lib/haml/helpers/action_view_mods.rb:15:in `render'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actiontext-6.1.5/app/helpers/action_text/content_helper.rb:25:in `block (2 levels) in render_action_text_attachments'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actiontext-6.1.5/app/helpers/action_text/content_helper.rb:24:in `tap'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actiontext-6.1.5/app/helpers/action_text/content_helper.rb:24:in `block in render_action_text_attachments'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actiontext-6.1.5/lib/action_text/content.rb:62:in `block in render_attachments'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actiontext-6.1.5/lib/action_text/fragment.rb:40:in `block (2 levels) in replace'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/nokogiri-1.13.4-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `block in each'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/nokogiri-1.13.4-x86_64-linux/lib/nokogiri/xml/node_set.rb:233:in `upto'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/nokogiri-1.13.4-x86_64-linux/lib/nokogiri/xml/node_set.rb:233:in `each'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actiontext-6.1.5/lib/action_text/fragment.rb:39:in `block in replace'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actiontext-6.1.5/lib/action_text/fragment.rb:33:in `update'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actiontext-6.1.5/lib/action_text/fragment.rb:38:in `replace'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actiontext-6.1.5/lib/action_text/content.rb:61:in `render_attachments'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actiontext-6.1.5/app/helpers/action_text/content_helper.rb:22:in `render_action_text_attachments'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actiontext-6.1.5/app/helpers/action_text/content_helper.rb:14:in `render_action_text_content'
/var/www/violet/shared/bundle/ruby/2.6.0/gems/actiontext-6.1.5/app/views/action_text/content/_layout.html.erb:2:in `__var_www_violet_shared_bundle_ruby_______gems_actiontext_______app_views_action_text_content__layout_html_erb___4101413755103500869_47346901922380'
```

**Comment by donrestarone** [comment]
the issue is here: https://github.com/restarone/violet_rails/pull/424/files

the emails go out when we dont render action text rich text blobs with attachments

**Comment by donrestarone** [comment]
affecting 1 client so far
![Screenshot from 2022-04-21 11-52-24](https://user-images.githubusercontent.com/35935196/164500925-4471a2f7-ff14-4b07-a3f9-ae4544cd7fb1.png)
