### ISSUE TITLE
Any layout other than default has empty head tags

### ISSUE THREAD

**Issue by Ayon95** [restarone/violet_rails#491]
If you create a new layout and use that for a page, its head tag doesn't get any content (no styles, meta tags, scripts and so on).

Steps to reproduce the problem:

1) Log into a Violet Rails app
2) Create a new layout under Layouts
3) Create a new page as a child of root, and have that page use that new layout

![Capture1](https://user-images.githubusercontent.com/73725297/165782423-ceb88b9c-3a0a-4ba3-b900-694a5dab09b4.PNG)
![Capture2](https://user-images.githubusercontent.com/73725297/165782439-80270f01-772f-4667-88eb-398566709e5b.PNG)
![Capture3](https://user-images.githubusercontent.com/73725297/165782456-2d9642b5-df47-40c5-a904-0d7888b9efd9.PNG)

**Comment by donrestarone** [comment]
This is what the app does when a layout other than default is used: 

``` txt
solutions_app        | Started GET "/test" for 192.168.32.1 at 2022-05-14 23:17:53 +0000
solutions_app        |   Subdomain Load (0.7ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   Subdomain Load (0.6ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   Subdomain Load (0.9ms)  SELECT "public"."subdomains".* FROM "public"."subdomains"
solutions_app        |   ↳ config/initializers/apartment.rb:54:in `each_with_object'
solutions_app        | Processing by Comfy::Cms::ContentController#show as HTML
solutions_app        |   Parameters: {"cms_path"=>"test"}
solutions_app        |   User Load (0.9ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
solutions_app        |   ↳ app/controllers/application_controller.rb:36:in `prepare_exception_notifier'
solutions_app        |    (0.7ms)  SELECT COUNT(*) FROM "comfy_cms_sites"
solutions_app        |   Comfy::Cms::Site Load (0.6ms)  SELECT "comfy_cms_sites".* FROM "comfy_cms_sites" ORDER BY "comfy_cms_sites"."id" ASC LIMIT $1  [["LIMIT", 1]]
solutions_app        |   Comfy::Cms::Page Load (0.7ms)  SELECT "comfy_cms_pages".* FROM "comfy_cms_pages" WHERE "comfy_cms_pages"."site_id" = $1 AND "comfy_cms_pages"."is_published" = $2 AND "comfy_cms_pages"."full_path" = $3 LIMIT $4  [["site_id", 1], ["is_published", true], ["full_path", "/test"], ["LIMIT", 1]]
solutions_app        |   Comfy::Cms::Layout Load (0.6ms)  SELECT "comfy_cms_layouts".* FROM "comfy_cms_layouts" WHERE "comfy_cms_layouts"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
solutions_app        |   Subdomain Load (0.6ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   Subdomain Load (0.6ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   Ahoy::Visit Load (0.8ms)  SELECT "ahoy_visits".* FROM "ahoy_visits" WHERE "ahoy_visits"."visit_token" = $1 ORDER BY "ahoy_visits"."id" ASC LIMIT $2  [["visit_token", "cdc0ce2c-b842-4ed2-9602-20eb9d3775db"], ["LIMIT", 1]]
solutions_app        |   ↳ config/initializers/comfortable_mexican_sofa.rb:17:in `authenticate'
solutions_app        |   TRANSACTION (0.6ms)  BEGIN
solutions_app        |   ↳ config/initializers/comfortable_mexican_sofa.rb:18:in `authenticate'
solutions_app        |   Ahoy::Event Create (32.5ms)  INSERT INTO "ahoy_events" ("visit_id", "user_id", "name", "properties", "time") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["visit_id", 22776], ["user_id", 1], ["name", "comfy-cms-page-visit"], ["properties", "{\"visit_id\":22776,\"comfy_cms_page_id\":4,\"user_id\":1}"], ["time", "2022-05-14 23:17:53.588519"]]
solutions_app        |   ↳ config/initializers/comfortable_mexican_sofa.rb:18:in `authenticate'
solutions_app        |   TRANSACTION (6.3ms)  COMMIT
solutions_app        |   ↳ config/initializers/comfortable_mexican_sofa.rb:18:in `authenticate'
solutions_app        |    (1.1ms)  SELECT "comfy_cms_pages"."full_path" FROM "comfy_cms_pages" WHERE "comfy_cms_pages"."is_restricted" = $1  [["is_restricted", true]]
solutions_app        |   ↳ config/initializers/comfortable_mexican_sofa.rb:23:in `authenticate'
solutions_app        |   Comfy::Cms::Fragment Load (0.7ms)  SELECT "comfy_cms_fragments".* FROM "comfy_cms_fragments" WHERE "comfy_cms_fragments"."record_id" = $1 AND "comfy_cms_fragments"."record_type" = $2  [["record_id", 4], ["record_type", "Comfy::Cms::Page"]]
solutions_app        |   Rendering inline template
solutions_app        |   Rendered inline template (Duration: 0.4ms | Allocations: 67)
solutions_app        | Completed 200 OK in 63ms (Views: 0.9ms | ActiveRecord: 46.5ms | Allocations: 12585)
solutions_app        |
solutions_app        |

```

this is what the app does when the default layout is used: 

``` txt
solutions_app        | Started GET "/" for 192.168.32.1 at 2022-05-14 23:19:21 +0000
solutions_app        |   Subdomain Load (0.7ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   Subdomain Load (0.7ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   Subdomain Load (0.7ms)  SELECT "public"."subdomains".* FROM "public"."subdomains"
solutions_app        |   ↳ config/initializers/apartment.rb:54:in `each_with_object'
solutions_app        | Processing by Comfy::Cms::ContentController#show as HTML
solutions_app        |   User Load (0.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
solutions_app        |   ↳ app/controllers/application_controller.rb:36:in `prepare_exception_notifier'
solutions_app        |    (0.6ms)  SELECT COUNT(*) FROM "comfy_cms_sites"
solutions_app        |   Comfy::Cms::Site Load (0.6ms)  SELECT "comfy_cms_sites".* FROM "comfy_cms_sites" ORDER BY "comfy_cms_sites"."id" ASC LIMIT $1  [["LIMIT", 1]]
solutions_app        |   Comfy::Cms::Page Load (0.6ms)  SELECT "comfy_cms_pages".* FROM "comfy_cms_pages" WHERE "comfy_cms_pages"."site_id" = $1 AND "comfy_cms_pages"."is_published" = $2 AND "comfy_cms_pages"."full_path" = $3 LIMIT $4  [["site_id", 1], ["is_published", true], ["full_path", "/"], ["LIMIT", 1]]
solutions_app        |   Comfy::Cms::Layout Load (0.5ms)  SELECT "comfy_cms_layouts".* FROM "comfy_cms_layouts" WHERE "comfy_cms_layouts"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
solutions_app        |   Subdomain Load (0.5ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   Subdomain Load (0.5ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   Ahoy::Visit Load (0.7ms)  SELECT "ahoy_visits".* FROM "ahoy_visits" WHERE "ahoy_visits"."visit_token" = $1 ORDER BY "ahoy_visits"."id" ASC LIMIT $2  [["visit_token", "cdc0ce2c-b842-4ed2-9602-20eb9d3775db"], ["LIMIT", 1]]
solutions_app        |   ↳ config/initializers/comfortable_mexican_sofa.rb:17:in `authenticate'
solutions_app        |   TRANSACTION (0.6ms)  BEGIN
solutions_app        |   ↳ config/initializers/comfortable_mexican_sofa.rb:18:in `authenticate'
solutions_app        |   Ahoy::Event Create (0.8ms)  INSERT INTO "ahoy_events" ("visit_id", "user_id", "name", "properties", "time") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["visit_id", 22776], ["user_id", 1], ["name", "comfy-cms-page-visit"], ["properties", "{\"visit_id\":22776,\"comfy_cms_page_id\":1,\"user_id\":1}"], ["time", "2022-05-14 23:19:21.057186"]]
solutions_app        |   ↳ config/initializers/comfortable_mexican_sofa.rb:18:in `authenticate'
solutions_app        |   TRANSACTION (5.6ms)  COMMIT
solutions_app        |   ↳ config/initializers/comfortable_mexican_sofa.rb:18:in `authenticate'
solutions_app        |    (0.6ms)  SELECT "comfy_cms_pages"."full_path" FROM "comfy_cms_pages" WHERE "comfy_cms_pages"."is_restricted" = $1  [["is_restricted", true]]
solutions_app        |   ↳ config/initializers/comfortable_mexican_sofa.rb:23:in `authenticate'
solutions_app        |   Comfy::Cms::Fragment Load (0.9ms)  SELECT "comfy_cms_fragments".* FROM "comfy_cms_fragments" WHERE "comfy_cms_fragments"."record_id" = $1 AND "comfy_cms_fragments"."record_type" = $2  [["record_id", 1], ["record_type", "Comfy::Cms::Page"]]
solutions_app        |   Rendering layout layouts/website.html.erb
solutions_app        |   Rendering inline template within layouts/website
solutions_app        |   Rendered inline template within layouts/website (Duration: 0.3ms | Allocations: 66)
solutions_app        |   Subdomain Load (0.9ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   Subdomain Load (1.2ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        | [Webpacker] Everything's up-to-date. Nothing to do
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   ActiveStorage::Attachment Load (0.9ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 23], ["record_type", "Subdomain"], ["name", "favicon"], ["LIMIT", 1]]
solutions_app        |   ↳ app/views/shared/_favicons.haml:1
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   CACHE ActiveStorage::Attachment Load (0.0ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 23], ["record_type", "Subdomain"], ["name", "favicon"], ["LIMIT", 1]]
solutions_app        |   ↳ app/views/shared/_favicons.haml:2
solutions_app        |   ActiveStorage::Blob Load (0.9ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 802], ["LIMIT", 1]]
solutions_app        |   ↳ app/views/shared/_favicons.haml:2
solutions_app        |   Rendered shared/_favicons.haml (Duration: 8.5ms | Allocations: 5121)
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   ActiveStorage::Attachment Load (0.7ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 23], ["record_type", "Subdomain"], ["name", "og_image"], ["LIMIT", 1]]
solutions_app        |   ↳ app/helpers/subdomain_helper.rb:70:in `og_image_url'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   Rendered shared/_meta_tags.html.erb (Duration: 11.3ms | Allocations: 11246)
solutions_app        |   Rendered shared/_file_download.haml (Duration: 0.1ms | Allocations: 22)
solutions_app        |   Rendered shared/_flash.haml (Duration: 0.2ms | Allocations: 129)
solutions_app        |   Rendered shared/navbars/_web_admin.html.haml (Duration: 0.2ms | Allocations: 69)
solutions_app        |   Rendered layout layouts/website.html.erb (Duration: 36.4ms | Allocations: 35910)
solutions_app        | Completed 200 OK in 62ms (Views: 32.1ms | ActiveRecord: 17.6ms | Allocations: 48443)
solutions_app        |
solutions_app        |
solutions_app        | Started GET "/cms-css/1/default.css" for 192.168.32.1 at 2022-05-14 23:19:21 +0000
solutions_app        | Started GET "/cms-js/1/default.js" for 192.168.32.1 at 2022-05-14 23:19:21 +0000
solutions_app        |   Subdomain Load (0.6ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   Subdomain Load (1.7ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   Subdomain Load (0.7ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   Subdomain Load (1.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "public"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   ↳ app/models/subdomain.rb:58:in `current'
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   CACHE Subdomain Load (0.0ms)  SELECT "public"."subdomains".* FROM "public"."subdomains" WHERE "public"."subdomains"."name" = $1 LIMIT $2  [["name", "root"], ["LIMIT", 1]]
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   ↳ app/models/subdomain.rb:62:in `current'
solutions_app        |   Subdomain Load (1.1ms)  SELECT "public"."subdomains".* FROM "public"."subdomains"
solutions_app        |   ↳ config/initializers/apartment.rb:54:in `each_with_object'
solutions_app        |   Subdomain Load (1.5ms)  SELECT "public"."subdomains".* FROM "public"."subdomains"
solutions_app        |   ↳ config/initializers/apartment.rb:54:in `each_with_object'
solutions_app        | Processing by Comfy::Cms::AssetsController#render_js as JS
solutions_app        |   Parameters: {"site_id"=>"1", "identifier"=>"default"}
solutions_app        | Processing by Comfy::Cms::AssetsController#render_css as CSS
solutions_app        |   User Load (2.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
solutions_app        |   Parameters: {"site_id"=>"1", "identifier"=>"default"}
solutions_app        |   ↳ app/controllers/application_controller.rb:36:in `prepare_exception_notifier'
solutions_app        |   User Load (2.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
solutions_app        |   ↳ app/controllers/application_controller.rb:36:in `prepare_exception_notifier'
solutions_app        |   Comfy::Cms::Site Load (4.4ms)  SELECT "comfy_cms_sites".* FROM "comfy_cms_sites" WHERE "comfy_cms_sites"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
solutions_app        |   Comfy::Cms::Site Load (1.8ms)  SELECT "comfy_cms_sites".* FROM "comfy_cms_sites" WHERE "comfy_cms_sites"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
solutions_app        |   Comfy::Cms::Layout Load (2.5ms)  SELECT "comfy_cms_layouts".* FROM "comfy_cms_layouts" WHERE "comfy_cms_layouts"."site_id" = $1 AND "comfy_cms_layouts"."identifier" = $2 LIMIT $3  [["site_id", 1], ["identifier", "default"], ["LIMIT", 1]]
solutions_app        |   Rendering text template
solutions_app        |   Rendered text template (Duration: 0.0ms | Allocations: 1)
solutions_app        | Completed 200 OK in 19ms (Views: 0.6ms | ActiveRecord: 9.1ms | Allocations: 6773)
solutions_app        |
solutions_app        |
solutions_app        |   Comfy::Cms::Layout Load (3.8ms)  SELECT "comfy_cms_layouts".* FROM "comfy_cms_layouts" WHERE "comfy_cms_layouts"."site_id" = $1 AND "comfy_cms_layouts"."identifier" = $2 LIMIT $3  [["site_id", 1], ["identifier", "default"], ["LIMIT", 1]]
solutions_app        |   Rendering text template
solutions_app        |   Rendered text template (Duration: 0.0ms | Allocations: 1)
solutions_app        | Completed 200 OK in 17ms (Views: 0.7ms | ActiveRecord: 7.8ms | Allocations: 6729)
solutions_app        |
solutions_app        |

```

**Comment by donrestarone** [comment]
This is why it works for the default layout but none of the other ones: https://github.com/restarone/violet_rails/blob/master/app/models/subdomain.rb#L197

the CMS layout expects to be told which layout to use. in our case we have a layout specifically for the 'website': 

https://github.com/restarone/violet_rails/blob/master/app/views/layouts/website.html.erb

**Comment by donrestarone** [comment]
affecting nikean.org
