### ISSUE TITLE
NoMethodError occurred in api_resources#show

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#947]
cant visit API Resource by click on ID on this screen: 
![Screenshot from 2022-07-20 19-35-53](https://user-images.githubusercontent.com/35935196/180100293-c2176936-47a7-42d2-918c-0cf3d8011069.png)

``` txt
A NoMethodError occurred in api_resources#show:

  undefined method `success_message' for nil:NilClass
  app/controllers/concerns/api_actionable.rb:110:in `execute_api_actions'

```

**Comment by donrestarone** [comment]
Happens when looking at the subdomain/events plugin action log: https://github.com/restarone/violet_rails/wiki/API-Namespace-plugin:-subdomain-events-V1

**Comment by donrestarone** [comment]
affecting `nikean.org`: 

``` txt
A NoMethodError occurred in api_resources#show:

  undefined method `success_message' for nil:NilClass
  app/controllers/concerns/api_actionable.rb:111:in `execute_api_actions'
```
